name: Maven Build with Report

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and run tests with Maven
        run: mvn clean test

      - name: List contents of surefire-reports (debug)
        run: |
          if [ -d target/surefire-reports ]; then
            echo "✅ Surefire reports found:"
            ls -l target/surefire-reports
          else
            echo "❌ No surefire reports found!"
          fi

      - name: Upload Surefire Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-report
          path: target/surefire-reports/
          if-no-files-found: warn
