name: Maven Build with HTML Report

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests and generate HTML report
        run: |
          mvn clean test
          mvn surefire-report:report-only site

      - name: Debug: Show HTML report location
        run: ls -R target/site

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-test-report
          path: target/site/
          if-no-files-found: warn
